services:
  - type: cron
    name: gold-telegram-cron
    runtime: node
    schedule: "*/5 * * * *"
    envVars:
      - key: METALS_API_KEY
        sync: false
      - key: TG_TOKEN
        sync: false
      - key: THRESHOLD_USD
        value: "0"
      - key: LOCAL_TZ
        value: "Asia/Phnom_Penh"
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: "goldbot"
      - key: MONGODB_COLL
        value: "subscribers"
    buildCommand: "npm ci"
    startCommand: "npm start"

  - type: web
    name: gold-telegram-webhook
    runtime: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm run web"
    envVars:
      - key: TG_WEBHOOK_SECRET
        sync: false
      - key: TG_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: "goldbot"
      - key: MONGODB_COLL
        value: "subscribers"
