services:
  # A) CRON: ยิงตามรอบเพื่อ broadcast เฉพาะ subscribers
  - type: cron
    name: gold-telegram-cron
    runtime: node
    schedule: "*/10 * * * *"
    envVars:
      - key: "WH0VIL5GXBQB33SIRAGI954SIRAGI"
        sync: false
      - key: "8340665740:AAGH14ja_3UG8IauSIg2ackhUru6KBMe1Ec"
        sync: false
      - key: THRESHOLD_USD
        value: "0"          # โหมดส่งทุกครั้ง
      - key: LOCAL_TZ
        value: "Asia/Phnom_Penh"
      - key: MONGODB_URI
        sync: false
      - key: "mongodb+srv://ronphearom2540:Phearom090790@cluster0.4ufedff.mongodb.net/yourdb?retryWrites=true&w=majority"
        value: "goldbot"
      - key: MONGODB_COLL
        value: "subscribers"
    buildCommand: "npm ci"
    startCommand: "npm start"

  # B) WEB: webhook รับ /start แล้วบันทึก chat_id -> MongoDB
  - type: web
    name: gold-telegram-webhook
    runtime: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm run web"
    envVars:
      - key: "33a42a7165b4230b8e3b64f20cb62432"
        sync: false
      - key: "mongodb+srv://ronphearom2540:Phearom090790@cluster0.4ufedff.mongodb.net/yourdb?retryWrites=true&w=majority"
        sync: false
      - key: MONGODB_DB
        value: "goldbot"
      - key: MONGODB_COLL
        value: "subscribers"
